=== ChrisQuint0/SARMS/group5-billing/billing.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT billing (record+)>
<!ELEMENT record (studentId, name, tuitionFee, paymentsMade, balance)>
<!ELEMENT studentId (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT tuitionFee (#PCDATA)>
<!ELEMENT paymentsMade (#PCDATA)>
<!ELEMENT balance (#PCDATA)>

=== ChrisQuint0/SARMS/group5-billing/billing.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="billing.xsl"?>
<!DOCTYPE billing SYSTEM "billing.dtd">
<billing xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="billing.xsd">
  <record>
    <studentId>BIL-001</studentId>
    <name>Sarah Williams</name>
    <tuitionFee>34478</tuitionFee>
    <paymentsMade>18603</paymentsMade>
    <balance>15875</balance>
  </record>
  <record>
    <studentId>BIL-002</studentId>
    <name>Robert Martin</name>
    <tuitionFee>21599</tuitionFee>
    <paymentsMade>6653</paymentsMade>
    <balance>14946</balance>
  </record>
  <record>
    <studentId>BIL-003</studentId>
    <name>Jane Rodriguez</name>
    <tuitionFee>46289</tuitionFee>
    <paymentsMade>42464</paymentsMade>
    <balance>3825</balance>
  </record>
  <record>
    <studentId>BIL-004</studentId>
    <name>Charles Anderson</name>
    <tuitionFee>37978</tuitionFee>
    <paymentsMade>16122</paymentsMade>
    <balance>21856</balance>
  </record>
  <record>
    <studentId>BIL-005</studentId>
    <name>Emily Lopez</name>
    <tuitionFee>42600</tuitionFee>
    <paymentsMade>38093</paymentsMade>
    <balance>4507</balance>
  </record>
  <record>
    <studentId>BIL-006</studentId>
    <name>Amelia Smith</name>
    <tuitionFee>36355</tuitionFee>
    <paymentsMade>12336</paymentsMade>
    <balance>24019</balance>
  </record>
  <record>
    <studentId>BIL-007</studentId>
    <name>Thomas Hernandez</name>
    <tuitionFee>46512</tuitionFee>
    <paymentsMade>11239</paymentsMade>
    <balance>35273</balance>
  </record>
  <record>
    <studentId>BIL-008</studentId>
    <name>James Garcia</name>
    <tuitionFee>45675</tuitionFee>
    <paymentsMade>40456</paymentsMade>
    <balance>5219</balance>
  </record>
  <record>
    <studentId>BIL-009</studentId>
    <name>Isabella Miller</name>
    <tuitionFee>34009</tuitionFee>
    <paymentsMade>27378</paymentsMade>
    <balance>6631</balance>
  </record>
  <record>
    <studentId>BIL-010</studentId>
    <name>Joseph Davis</name>
    <tuitionFee>36405</tuitionFee>
    <paymentsMade>22095</paymentsMade>
    <balance>14310</balance>
  </record>
  <record>
    <studentId>BIL-011</studentId>
    <name>Harper Jackson</name>
    <tuitionFee>25522</tuitionFee>
    <paymentsMade>19371</paymentsMade>
    <balance>6151</balance>
  </record>
  <record>
    <studentId>BIL-012</studentId>
    <name>Mia Martin</name>
    <tuitionFee>27277</tuitionFee>
    <paymentsMade>24487</paymentsMade>
    <balance>2790</balance>
  </record>
  <record>
    <studentId>BIL-013</studentId>
    <name>Matthew Jones</name>
    <tuitionFee>45618</tuitionFee>
    <paymentsMade>37301</paymentsMade>
    <balance>8317</balance>
  </record>
  <record>
    <studentId>BIL-014</studentId>
    <name>Harper Williams</name>
    <tuitionFee>30420</tuitionFee>
    <paymentsMade>24117</paymentsMade>
    <balance>6303</balance>
  </record>
  <record>
    <studentId>BIL-015</studentId>
    <name>Laura Gonzalez</name>
    <tuitionFee>48090</tuitionFee>
    <paymentsMade>42328</paymentsMade>
    <balance>5762</balance>
  </record>
  <record>
    <studentId>BIL-016</studentId>
    <name>Robert Hernandez</name>
    <tuitionFee>43323</tuitionFee>
    <paymentsMade>39539</paymentsMade>
    <balance>3784</balance>
  </record>
  <record>
    <studentId>BIL-017</studentId>
    <name>William Martinez</name>
    <tuitionFee>41831</tuitionFee>
    <paymentsMade>18771</paymentsMade>
    <balance>23060</balance>
  </record>
  <record>
    <studentId>BIL-018</studentId>
    <name>Evelyn Gonzalez</name>
    <tuitionFee>38676</tuitionFee>
    <paymentsMade>37467</paymentsMade>
    <balance>1209</balance>
  </record>
  <record>
    <studentId>BIL-019</studentId>
    <name>Harper Jackson</name>
    <tuitionFee>35059</tuitionFee>
    <paymentsMade>12281</paymentsMade>
    <balance>22778</balance>
  </record>
  <record>
    <studentId>BIL-020</studentId>
    <name>Mia Lopez</name>
    <tuitionFee>40917</tuitionFee>
    <paymentsMade>35564</paymentsMade>
    <balance>5353</balance>
  </record>
  <record>
    <studentId>BIL-021</studentId>
    <name>Thomas Lopez</name>
    <tuitionFee>40848</tuitionFee>
    <paymentsMade>3430</paymentsMade>
    <balance>37418</balance>
  </record>
  <record>
    <studentId>BIL-022</studentId>
    <name>Laura Anderson</name>
    <tuitionFee>45901</tuitionFee>
    <paymentsMade>3386</paymentsMade>
    <balance>42515</balance>
  </record>
  <record>
    <studentId>BIL-023</studentId>
    <name>John Jackson</name>
    <tuitionFee>42142</tuitionFee>
    <paymentsMade>40968</paymentsMade>
    <balance>1174</balance>
  </record>
  <record>
    <studentId>BIL-024</studentId>
    <name>Sarah Moore</name>
    <tuitionFee>43809</tuitionFee>
    <paymentsMade>37835</paymentsMade>
    <balance>5974</balance>
  </record>
  <record>
    <studentId>BIL-025</studentId>
    <name>Emma Hernandez</name>
    <tuitionFee>31197</tuitionFee>
    <paymentsMade>19112</paymentsMade>
    <balance>12085</balance>
  </record>
  <record>
    <studentId>BIL-026</studentId>
    <name>Thomas Moore</name>
    <tuitionFee>41063</tuitionFee>
    <paymentsMade>19335</paymentsMade>
    <balance>21728</balance>
  </record>
  <record>
    <studentId>BIL-027</studentId>
    <name>Evelyn Thomas</name>
    <tuitionFee>25778</tuitionFee>
    <paymentsMade>13285</paymentsMade>
    <balance>12493</balance>
  </record>
  <record>
    <studentId>BIL-028</studentId>
    <name>Isabella Moore</name>
    <tuitionFee>20455</tuitionFee>
    <paymentsMade>7193</paymentsMade>
    <balance>13262</balance>
  </record>
  <record>
    <studentId>BIL-029</studentId>
    <name>Harper Miller</name>
    <tuitionFee>21495</tuitionFee>
    <paymentsMade>9134</paymentsMade>
    <balance>12361</balance>
  </record>
  <record>
    <studentId>BIL-030</studentId>
    <name>Emma Garcia</name>
    <tuitionFee>33366</tuitionFee>
    <paymentsMade>7364</paymentsMade>
    <balance>26002</balance>
  </record>
  <record>
    <studentId>BIL-031</studentId>
    <name>Charlotte Anderson</name>
    <tuitionFee>37101</tuitionFee>
    <paymentsMade>34924</paymentsMade>
    <balance>2177</balance>
  </record>
  <record>
    <studentId>BIL-032</studentId>
    <name>Amelia Wilson</name>
    <tuitionFee>27546</tuitionFee>
    <paymentsMade>3027</paymentsMade>
    <balance>24519</balance>
  </record>
  <record>
    <studentId>BIL-033</studentId>
    <name>Jane Garcia</name>
    <tuitionFee>40560</tuitionFee>
    <paymentsMade>9653</paymentsMade>
    <balance>30907</balance>
  </record>
  <record>
    <studentId>BIL-034</studentId>
    <name>Charles Jones</name>
    <tuitionFee>21523</tuitionFee>
    <paymentsMade>17621</paymentsMade>
    <balance>3902</balance>
  </record>
  <record>
    <studentId>BIL-035</studentId>
    <name>Alex Johnson</name>
    <tuitionFee>43217</tuitionFee>
    <paymentsMade>36109</paymentsMade>
    <balance>7108</balance>
  </record>
  <record>
    <studentId>BIL-036</studentId>
    <name>Emma Gonzalez</name>
    <tuitionFee>31860</tuitionFee>
    <paymentsMade>640</paymentsMade>
    <balance>31220</balance>
  </record>
  <record>
    <studentId>BIL-037</studentId>
    <name>Robert Davis</name>
    <tuitionFee>47482</tuitionFee>
    <paymentsMade>18231</paymentsMade>
    <balance>29251</balance>
  </record>
  <record>
    <studentId>BIL-038</studentId>
    <name>Charles Hernandez</name>
    <tuitionFee>32208</tuitionFee>
    <paymentsMade>7100</paymentsMade>
    <balance>25108</balance>
  </record>
  <record>
    <studentId>BIL-039</studentId>
    <name>Harper Johnson</name>
    <tuitionFee>32953</tuitionFee>
    <paymentsMade>32772</paymentsMade>
    <balance>181</balance>
  </record>
  <record>
    <studentId>BIL-040</studentId>
    <name>Olivia Hernandez</name>
    <tuitionFee>42761</tuitionFee>
    <paymentsMade>19177</paymentsMade>
    <balance>23584</balance>
  </record>
  <record>
    <studentId>BIL-041</studentId>
    <name>Emma Thomas</name>
    <tuitionFee>42404</tuitionFee>
    <paymentsMade>2677</paymentsMade>
    <balance>39727</balance>
  </record>
  <record>
    <studentId>BIL-042</studentId>
    <name>Olivia Williams</name>
    <tuitionFee>27884</tuitionFee>
    <paymentsMade>8446</paymentsMade>
    <balance>19438</balance>
  </record>
  <record>
    <studentId>BIL-043</studentId>
    <name>Olivia Jackson</name>
    <tuitionFee>28635</tuitionFee>
    <paymentsMade>27448</paymentsMade>
    <balance>1187</balance>
  </record>
  <record>
    <studentId>BIL-044</studentId>
    <name>Emily Jackson</name>
    <tuitionFee>24164</tuitionFee>
    <paymentsMade>18483</paymentsMade>
    <balance>5681</balance>
  </record>
  <record>
    <studentId>BIL-045</studentId>
    <name>Michael Williams</name>
    <tuitionFee>31588</tuitionFee>
    <paymentsMade>10471</paymentsMade>
    <balance>21117</balance>
  </record>
  <record>
    <studentId>BIL-046</studentId>
    <name>Thomas Miller</name>
    <tuitionFee>33830</tuitionFee>
    <paymentsMade>16032</paymentsMade>
    <balance>17798</balance>
  </record>
  <record>
    <studentId>BIL-047</studentId>
    <name>Evelyn Rodriguez</name>
    <tuitionFee>35793</tuitionFee>
    <paymentsMade>6069</paymentsMade>
    <balance>29724</balance>
  </record>
  <record>
    <studentId>BIL-048</studentId>
    <name>James Smith</name>
    <tuitionFee>44226</tuitionFee>
    <paymentsMade>20838</paymentsMade>
    <balance>23388</balance>
  </record>
  <record>
    <studentId>BIL-049</studentId>
    <name>Anthony Jones</name>
    <tuitionFee>39651</tuitionFee>
    <paymentsMade>30091</paymentsMade>
    <balance>9560</balance>
  </record>
  <record>
    <studentId>BIL-050</studentId>
    <name>Amelia Lopez</name>
    <tuitionFee>41978</tuitionFee>
    <paymentsMade>38926</paymentsMade>
    <balance>3052</balance>
  </record>
  <record>
    <studentId>BIL-051</studentId>
    <name>David Brown</name>
    <tuitionFee>40522</tuitionFee>
    <paymentsMade>30609</paymentsMade>
